services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${NGINX_PORT:-8080}:80"
  #   depends_on:
  #     - main
  #     - minio
  #   networks:
  #     - app_network
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    ports:
      - 5432:5432
    networks:
      - app_network

  main:
    build:
      context: ./main
    depends_on:
      - db
      - chromadb
      - minio
    env_file:
      - .env
    environment:
      - APP_ENV=prod
    ports:
      - 8000:8000
    volumes:
      - ./main:/app:delegated
    restart: unless-stopped
    networks:
      - app_network

  celery-worker:
    build:
      context: ./main
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint-celery.sh"]
    env_file:
      - .env
    environment:
      - CELERY_MODE=worker
    depends_on:
      - rabbitmq
      - main
    volumes:
      - ./main:/app
    networks:
      - app_network
    restart: unless-stopped

  celery-beat:
    build:
      context: ./main
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint-celery.sh"]
    env_file:
      - .env
    environment:
      - CELERY_MODE=beat
    depends_on:
      - rabbitmq
      - main
      - celery-worker
    volumes:
      - ./main:/app
    networks:
      - app_network
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:1.1.0
    ports:
      - 8001:8000
    volumes:
      - chroma_data:/data
    networks:
      - app_network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - 9000:9000 # API port
      - 9001:9001 # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-rabbitmq}
    ports:
      - "5672:5672"
      - "15672:15672"  # management console
    networks:
      - app_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flower:
    image: mher/flower
    env_file:
      - .env
    command: >
      celery
        --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//
        --result-backend=rpc://
        flower
        --address=0.0.0.0
        --port=${FLOWER_PORT:-5555}
        --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin123}
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    depends_on:
      - rabbitmq
      - celery-worker
    networks:
      - app_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  script:
    build:
      context: ./script
    depends_on:
      - main
    environment:
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    volumes:
      - ./script:/app
    tty: true
    command: ["tail", "-f", "/dev/null"]
    networks:
      - app_network

volumes:
  pg-data:
  chroma_data:
  minio_data:

networks:
  app_network:
    driver: bridge