services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${NGINX_PORT:-8080}:80"
  #   depends_on:
  #     - main
  #     - minio
  #   networks:
  #     - app_network
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    ports:
      - 5432:5432
    networks:
      - app_network

  main:
    build:
      context: ./main
    depends_on:
      - db
      - chromadb
      - minio
    env_file:
      - .env
    environment:
      - APP_ENV=prod
    ports:
      - 8000:8000
    volumes:
      - ./main:/app:delegated
    restart: unless-stopped
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma:1.1.0
    ports:
      - 8001:8000
    volumes:
      - chroma_data:/data
    networks:
      - app_network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - 9000:9000 # API port
      - 9001:9001 # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network

  script:
    build:
      context: ./script
    depends_on:
      - main
    environment:
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    volumes:
      - ./script:/app
    tty: true
    command: ["tail", "-f", "/dev/null"]
    networks:
      - app_network

volumes:
  pg-data:
  chroma_data:
  minio_data:

networks:
  app_network:
    driver: bridge