services:
  # nginx:
  #   ports: !override
  #     - "${NGINX_PORT:-8080}:80"

  main:
    volumes:
      - ./main:/app:delegated
    environment:
      - APP_ENV=dev
    ports: !override
      - "${APP_PORT}:8000"

  chromadb:
    ports: !override
      - 8101:8000

  minio:
    ports: !override
      - 9100:9000 # API port
      - 9101:9001 # Console port

  rabbitmq:
    ports: !override
      - "${RABBITMQ_MGMT_PORT:-15673}:15672"  # mgmt UI port override

  flower:
    ports: !override
      - "5556:5555"
    depends_on:
      - rabbitmq
      - celery-worker

  pgadmin:
    image: dpage/pgadmin4:9.7.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - 5550:80
    networks:
      - app_network

volumes:
  pg-admin-data: